/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project3.View;

import java.awt.Toolkit;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URI;

/**
 *
 * @author lenoco
 */
public class seven extends javax.swing.JFrame {

    /**
     * Creates new form seven
     */
    public seven() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel2.setText("Guided Visualization with Breathing");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI Historic", 0, 8)); // NOI18N
        jLabel42.setText("2. Close your eyes and relax by breathing slowly and deeply.");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 10));

        jLabel14.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel14.setText("FOR VIDEO LINK, CLICK HERE: ");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jButton1.setText("Video");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 223, 80, 30));

        jLabel43.setFont(new java.awt.Font("Segoe UI Historic", 0, 8)); // NOI18N
        jLabel43.setText("3. Visualize the color you’ve chosen.");
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 10));

        jLabel44.setFont(new java.awt.Font("Segoe UI Historic", 0, 8)); // NOI18N
        jLabel44.setText("represents for you.");
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 10));

        jLabel45.setFont(new java.awt.Font("Segoe UI Historic", 0, 8)); // NOI18N
        jLabel45.setText("4. Continue breathing while holding that color in your thoughts, thinking about what it");
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 10));

        jLabel46.setFont(new java.awt.Font("Segoe UI Historic", 0, 8)); // NOI18N
        jLabel46.setText("5. With each inhale, imagine the desired color slowly washing over your body from");
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 10));

        jLabel47.setFont(new java.awt.Font("Segoe UI Historic", 0, 8)); // NOI18N
        jLabel47.setText("head to toe. Continue breathing as you visualize the color filling your entire body,");
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 10));

        jLabel48.setFont(new java.awt.Font("Segoe UI Historic", 0, 8)); // NOI18N
        jLabel48.setText("including your fingertips and toes.");
        getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 10));

        jLabel49.setFont(new java.awt.Font("Segoe UI Historic", 0, 8)); // NOI18N
        jLabel49.setText("6. Imagine any unwanted emotions draining out of your body with each exhale, and");
        getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 10));

        jLabel50.setFont(new java.awt.Font("Segoe UI Historic", 0, 8)); // NOI18N
        jLabel50.setText("replace them with your chosen color with each inhale.");
        getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 10));

        jLabel51.setFont(new java.awt.Font("Segoe UI Historic", 0, 8)); // NOI18N
        jLabel51.setText("7. Continue the visualization as long as you like. You might feel lightened and more");
        getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 10));

        jLabel52.setFont(new java.awt.Font("Segoe UI Historic", 0, 8)); // NOI18N
        jLabel52.setText("peaceful after just a minute or two.");
        getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 10));

        jLabel53.setFont(new java.awt.Font("Segoe UI Historic", 0, 8)); // NOI18N
        jLabel53.setText("1. Get comfortable, just as you would for ordinary meditation.");
        getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 10));

        jButton2.setText("<-");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 223, 60, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project3/View/pics/Breathbg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            URI uri = new URI("https://youtu.be/qcdbCphVa1g?si=pwiCr8ebjTlorbxn");
            java.awt.Desktop.getDesktop().browse(uri);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // open BreathingTechniques
        BreathingTechniques breathingtechniques = new BreathingTechniques();
        breathingtechniques.show(); // display BreathingTechniques here

        dispose(); // close page after opening BreathingTechniques
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seven().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    // End of variables declaration//GEN-END:variables

  
}
